import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import streamersRouter from "./streamers";
import kingdomsRouter from "./kingdoms";
import sessionsRouter from "./sessions";
import automationsRouter from "./automations";
import gamificationRouter from "./gamification";
import bossBattlesRouter from "./boss-battles";
import miniGamesRouter from "./mini-games";
import universeRouter from "./universe";
import obsRouter from "./obs";
import aiRouter from "./ai";
import billingRouter from "./billing";
import adminRouter from "./admin";
import tiktokRouter from "./tiktok";
import integrationsRouter from "./integrations";
import devRouter from "./dev";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(streamersRouter);
router.use(kingdomsRouter);
router.use(sessionsRouter);
router.use(automationsRouter);
router.use(gamificationRouter);
router.use(bossBattlesRouter);
router.use(miniGamesRouter);
router.use(universeRouter);
router.use(obsRouter);
router.use(aiRouter);
router.use(tiktokRouter);
router.use(integrationsRouter);
router.use(billingRouter);
router.use(adminRouter);
router.use(devRouter);

export default router;
