#!/usr/bin/env python3
"""Generate 100 original SYLORA gift specifications (SPEC ONLY by default).

READY status is assigned only by the asset build + validation pipeline after
real Blender/GLB/audio/preview/runtime checks succeed — never by this script alone.
"""

from __future__ import annotations

import json
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "artifacts" / "gift-library"

# Map user-facing rarity -> SYLORA API GiftTier
API_TIER = {
    "Rare": "rare",
    "Epic": "epic",
    "Legendary": "legendary",
    "Mythic": "mythical",
    "Divine": "ultra_premium",
}

PRICE_LADDER = [
    10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000,
    25000, 50000, 100000, 250000, 500000, 1000000, 2500000, 5000000, 10000000,
]

# Each entry is a unique concept — different form, story, environment, VFX vocabulary.
# VFX keys are story-matched; fire/smoke/lightning only when the plot needs them.
GIFTS: list[dict] = [
    # -------- Rare (20): short, beautiful, mobile-light --------
    {
        "name": "Lumen Seed",
        "slug": "lumen-seed",
        "rarity": "Rare",
        "price": 10,
        "duration_ms": 3200,
        "idea": "A single luminous seed cracks open into a soft SYLORA crest of light.",
        "model": "Faceted seed pod with translucent shell and internal filament core.",
        "environment": "Floating void with faint radial floor glow; no room geometry.",
        "phases": ["dormant float", "shell fracture", "filament bloom", "crest settle"],
        "vfx": ["caustic refract", "soft spark motes"],
        "particles": "warm pollen motes (low count)",
        "shaders": ["thin-film shell", "emissive filament"],
        "camera": "gentle push-in, slight orbit",
        "music": "single piano harmonic swell",
        "spatial": "center-to-wide bloom",
        "voice": "none",
        "form_family": "organic_seed",
        "vfx_family": "light_refract",
    },
    {
        "name": "Paper Koi",
        "slug": "paper-koi",
        "rarity": "Rare",
        "price": 25,
        "duration_ms": 4000,
        "idea": "An origami koi unfolds mid-air and glides once around the avatar.",
        "model": "Low-poly origami koi with crease normals and paper grain maps.",
        "environment": "Shallow reflective plane suggesting a pond surface.",
        "phases": ["folded square", "unfold wings", "glide arc", "settle bow"],
        "vfx": ["water-ripple rings (story water only)", "paper dust"],
        "particles": "confetti-scale paper flecks",
        "shaders": ["anisotropic paper", "wet tip specular"],
        "camera": "side tracking shot",
        "music": "plucked koto motif",
        "spatial": "left-to-right pan with koi",
        "voice": "soft paper rustle SFX as voice-like texture",
        "form_family": "origami_animal",
        "vfx_family": "water_ripple",
    },
    {
        "name": "Signal Ribbon",
        "slug": "signal-ribbon",
        "rarity": "Rare",
        "price": 25,
        "duration_ms": 3600,
        "idea": "A neon ribbon of chat energy wraps the streamer nameplate once.",
        "model": "Parametric ribbon mesh with UV scroll stripes.",
        "environment": "Dark UI depth with soft bokeh dots.",
        "phases": ["ribbon spawn", "wrap nameplate", "pulse sync", "fade trail"],
        "vfx": ["UV scroll glow", "trail afterimage"],
        "particles": "tiny UI pixels",
        "shaders": ["emissive scroll", "additive trail"],
        "camera": "locked framing on lower-third",
        "music": "soft synth blip arpeggio",
        "spatial": "stereo wrap L/R",
        "voice": "none",
        "form_family": "ribbon",
        "vfx_family": "ui_glow",
    },
    {
        "name": "Tea Steam Heart",
        "slug": "tea-steam-heart",
        "rarity": "Rare",
        "price": 50,
        "duration_ms": 4200,
        "idea": "Steam from a ceramic cup briefly forms a heart silhouette.",
        "model": "Handmade cup, saucer, and volumetric steam proxy mesh.",
        "environment": "Warm desk vignette with soft window light.",
        "phases": ["cup present", "steam rise", "heart form", "dissolve"],
        "vfx": ["steam volume (smoke-like only as steam)", "heat shimmer"],
        "particles": "condensate droplets",
        "shaders": ["ceramic SSS", "steam opacity"],
        "camera": "macro dolly",
        "music": "soft ceramic chime",
        "spatial": "near-field cup center",
        "voice": "none",
        "form_family": "ceramic_prop",
        "vfx_family": "steam",
    },
    {
        "name": "Constellation Pin",
        "slug": "constellation-pin",
        "rarity": "Rare",
        "price": 50,
        "duration_ms": 3800,
        "idea": "Stars connect into a unique viewer-initial constellation.",
        "model": "Beveled pin body with star nodes and thin line segments.",
        "environment": "Night gradient with distant starfield plate.",
        "phases": ["pin drop", "stars ignite", "lines connect", "hold"],
        "vfx": ["star twinkle", "line draw"],
        "particles": "micro stardust",
        "shaders": ["metal pin", "emissive stars"],
        "camera": "top-down tilt to 3/4",
        "music": "celesta cluster",
        "spatial": "wide celestial",
        "voice": "none",
        "form_family": "jewelry_pin",
        "vfx_family": "star_draw",
    },
    {
        "name": "Ink Drop Bloom",
        "slug": "ink-drop-bloom",
        "rarity": "Rare",
        "price": 100,
        "duration_ms": 4000,
        "idea": "A drop of luminous ink blooms into a calligraphic flourish.",
        "model": "Fluid metaball drop morphing into ribbon calligraphy stroke.",
        "environment": "Paper grain plane under soft key light.",
        "phases": ["drop fall", "impact bloom", "stroke draw", "dry settle"],
        "vfx": ["ink diffusion", "paper absorb"],
        "particles": "micro ink beads",
        "shaders": ["viscous ink", "paper fiber"],
        "camera": "overhead then slight tilt",
        "music": "brush stroke whoosh + soft drone",
        "spatial": "close paper plane",
        "voice": "none",
        "form_family": "fluid_callig",
        "vfx_family": "ink_diffusion",
    },
    {
        "name": "Glass Marbles",
        "slug": "glass-marbles",
        "rarity": "Rare",
        "price": 100,
        "duration_ms": 3500,
        "idea": "Three glass marbles collide and ring a clear chord.",
        "model": "Three unique swirl-core marbles with different internal ribbons.",
        "environment": "Minimal reflective tray.",
        "phases": ["roll in", "collide", "bounce settle", "glow pulse"],
        "vfx": ["contact sparks (non-fire)", "caustics"],
        "particles": "tiny glass chips (very few)",
        "shaders": ["glass IOR", "internal swirl"],
        "camera": "low angle tracking",
        "music": "glass bowl chord",
        "spatial": "impact-centered stereo",
        "voice": "none",
        "form_family": "glass_spheres",
        "vfx_family": "caustic_glass",
    },
    {
        "name": "Wind Chime Gate",
        "slug": "wind-chime-gate",
        "rarity": "Rare",
        "price": 100,
        "duration_ms": 4500,
        "idea": "Bamboo chimes part like a gate for a soft breeze gift.",
        "model": "Bamboo tubes, cords, and wooden bar with soft cloth ties.",
        "environment": "Outdoor soft daylight haze.",
        "phases": ["still", "breeze start", "chimes part", "close bow"],
        "vfx": ["cloth flutter", "dust motes in sun"],
        "particles": "pollen in breeze",
        "shaders": ["bamboo anisotropy", "cloth"],
        "camera": "through-gate push",
        "music": "tuned bamboo hits",
        "spatial": "wide outdoor",
        "voice": "none",
        "form_family": "bamboo_chime",
        "vfx_family": "breeze_motes",
    },
    {
        "name": "Polaroid Flash",
        "slug": "polaroid-flash",
        "rarity": "Rare",
        "price": 250,
        "duration_ms": 3800,
        "idea": "A vintage instant photo ejects and develops the streamer silhouette.",
        "model": "Instant camera body and ejecting photo card with develop shader.",
        "environment": "Soft studio seamless.",
        "phases": ["camera click", "eject", "develop reveal", "float hold"],
        "vfx": ["flash bloom (no lens spam)", "develop dissolve"],
        "particles": "none heavy — flash residue only",
        "shaders": ["plastic body", "photo develop mask"],
        "camera": "hero product then card close-up",
        "music": "shutter + warm chord",
        "spatial": "flash front then card near",
        "voice": "none",
        "form_family": "camera_prop",
        "vfx_family": "photo_develop",
    },
    {
        "name": "Moon Phase Coin",
        "slug": "moon-phase-coin",
        "rarity": "Rare",
        "price": 250,
        "duration_ms": 4000,
        "idea": "A coin flips through lunar phases and lands on a glowing side.",
        "model": "Double-sided engraved coin with phase relief.",
        "environment": "Deep indigo void.",
        "phases": ["toss", "phase morph mid-spin", "land", "rim glow"],
        "vfx": ["phase silhouette wipe", "rim light"],
        "particles": "silver dust",
        "shaders": ["brushed metal", "phase emissive"],
        "camera": "spin-follow then settle",
        "music": "metallic spin + soft choir pad",
        "spatial": "spinning stereo image",
        "voice": "none",
        "form_family": "coin",
        "vfx_family": "phase_wipe",
    },
    {
        "name": "Coral Whisper",
        "slug": "coral-whisper",
        "rarity": "Rare",
        "price": 250,
        "duration_ms": 4200,
        "idea": "A small coral branch opens polyps that release bioluminescent beads.",
        "model": "Branching coral with animated polyp tips.",
        "environment": "Underwater blue haze (water required by story).",
        "phases": ["still coral", "polyps open", "beads rise", "fade"],
        "vfx": ["underwater godrays", "biolume beads"],
        "particles": "rising luminous beads",
        "shaders": ["SSS coral", "biolume"],
        "camera": "slow underwater drift",
        "music": "filtered soft pads",
        "spatial": "muffled underwater",
        "voice": "none",
        "form_family": "coral",
        "vfx_family": "biolume_water",
    },
    {
        "name": "Stamp Seal",
        "slug": "stamp-seal",
        "rarity": "Rare",
        "price": 50,
        "duration_ms": 3000,
        "idea": "A wax seal stamp presses and leaves a SYLORA crest impression.",
        "model": "Wooden handle stamp and wax puddle with crest negative.",
        "environment": "Letter desk with parchment.",
        "phases": ["raise stamp", "press", "lift reveal", "wax cool"],
        "vfx": ["wax squash", "cool harden"],
        "particles": "tiny wax flecks",
        "shaders": ["wax SSS", "wood grain"],
        "camera": "top-down press",
        "music": "soft thud + seal click",
        "spatial": "desk nearfield",
        "voice": "none",
        "form_family": "stamp",
        "vfx_family": "wax_press",
    },
    {
        "name": "Aurora Thread",
        "slug": "aurora-thread",
        "rarity": "Rare",
        "price": 100,
        "duration_ms": 4400,
        "idea": "A single aurora thread weaves a temporary halo above the avatar.",
        "model": "Thin ribbon spline with thickness variation.",
        "environment": "Night hillside silhouette.",
        "phases": ["thread appear", "weave halo", "color shift", "dissolve"],
        "vfx": ["aurora color bands", "soft bloom"],
        "particles": "ice crystal glitter",
        "shaders": ["additive aurora", "fresnel edge"],
        "camera": "low looking up",
        "music": "high string harmonic",
        "spatial": "overhead dome",
        "voice": "none",
        "form_family": "thread_ribbon",
        "vfx_family": "aurora",
    },
    {
        "name": "Gear Smile",
        "slug": "gear-smile",
        "rarity": "Rare",
        "price": 25,
        "duration_ms": 3600,
        "idea": "Tiny brass gears assemble into a smiling face then wink.",
        "model": "Interlocking gear set forming facial features.",
        "environment": "Workshop table with soft brass bounce light.",
        "phases": ["scatter gears", "assemble", "smile", "wink click"],
        "vfx": ["metal sparks (non-fire contact)", "oil sheen"],
        "particles": "brass filings",
        "shaders": ["brass PBR", "oil film"],
        "camera": "macro assemble",
        "music": "tick-tock melody",
        "spatial": "mechanical center",
        "voice": "none",
        "form_family": "gear_mech",
        "vfx_family": "mech_sparks",
    },
    {
        "name": "Snow Globe Peek",
        "slug": "snow-globe-peek",
        "rarity": "Rare",
        "price": 250,
        "duration_ms": 4500,
        "idea": "A snow globe shakes; inside, a tiny stage bows to the streamer.",
        "model": "Glass dome, base, and miniature stage set.",
        "environment": "Holiday soft bokeh (no fire).",
        "phases": ["shake", "snow swirl", "stage bow", "settle"],
        "vfx": ["snow swirl", "glass refraction"],
        "particles": "snow flakes",
        "shaders": ["glass dome", "velvet base"],
        "camera": "through-glass push",
        "music": "music-box phrase",
        "spatial": "inside-dome muffled then clear",
        "voice": "none",
        "form_family": "snow_globe",
        "vfx_family": "snow_swirl",
    },
    {
        "name": "Lantern Moth",
        "slug": "lantern-moth",
        "rarity": "Rare",
        "price": 100,
        "duration_ms": 4000,
        "idea": "A paper moth circles a hanging lantern and lands as a gift badge.",
        "model": "Lantern frame with paper panels; moth with wing membranes.",
        "environment": "Evening garden path.",
        "phases": ["lantern glow", "moth circle", "land", "badge form"],
        "vfx": ["lantern warm light", "wing translucency"],
        "particles": "night insects (sparse)",
        "shaders": ["paper translucency", "warm emissive"],
        "camera": "orbit around lantern",
        "music": "soft flute phrase",
        "spatial": "garden night",
        "voice": "none",
        "form_family": "lantern_insect",
        "vfx_family": "warm_lantern",
    },
    {
        "name": "Crystal Dice",
        "slug": "crystal-dice",
        "rarity": "Rare",
        "price": 50,
        "duration_ms": 3400,
        "idea": "A translucent d20 rolls and stops on a glowing face.",
        "model": "Beveled icosahedron with engraved numerals.",
        "environment": "Felt table top.",
        "phases": ["toss", "bounce", "stop", "face glow"],
        "vfx": ["face highlight", "micro sparkles"],
        "particles": "crystal dust",
        "shaders": ["crystal SSS", "engraved emissive"],
        "camera": "dice-follow",
        "music": "crystal clack chord",
        "spatial": "table bounce stereo",
        "voice": "none",
        "form_family": "polyhedra",
        "vfx_family": "crystal_glow",
    },
    {
        "name": "Bubble Quartet",
        "slug": "bubble-quartet",
        "rarity": "Rare",
        "price": 25,
        "duration_ms": 3800,
        "idea": "Four soap bubbles merge into one iridescent sphere.",
        "model": "Thin-film bubble spheres with merge morph.",
        "environment": "Soft pastel void.",
        "phases": ["four rise", "orbit", "merge", "pop shimmer"],
        "vfx": ["thin-film iridescence", "pop spray"],
        "particles": "micro droplets on pop",
        "shaders": ["thin film", "fresnel"],
        "camera": "float-level tracking",
        "music": "soft pop tones",
        "spatial": "airy stereo",
        "voice": "none",
        "form_family": "bubbles",
        "vfx_family": "iridescent_pop",
    },
    {
        "name": "Bookmark Ribbon",
        "slug": "bookmark-ribbon",
        "rarity": "Rare",
        "price": 10,
        "duration_ms": 3000,
        "idea": "A silk bookmark slips into an open book and marks a glowing page.",
        "model": "Open book and silk ribbon with fringe.",
        "environment": "Library shelf bokeh.",
        "phases": ["book open", "ribbon slide", "page glow", "hold"],
        "vfx": ["page light", "silk sheen"],
        "particles": "dust motes",
        "shaders": ["paper SSS", "silk anisotropy"],
        "camera": "page-level push",
        "music": "page turn + soft harp",
        "spatial": "quiet library",
        "voice": "none",
        "form_family": "book_prop",
        "vfx_family": "page_glow",
    },
    {
        "name": "Compass Kind",
        "slug": "compass-kind",
        "rarity": "Rare",
        "price": 100,
        "duration_ms": 4000,
        "idea": "A brass compass needle spins then locks toward the recipient.",
        "model": "Open compass with glass, needle, and engraved rose.",
        "environment": "Map table with soft lamp.",
        "phases": ["open lid", "spin", "lock", "beam tick"],
        "vfx": ["needle trail", "soft lock pulse"],
        "particles": "map dust",
        "shaders": ["brass", "glass dome"],
        "camera": "top-down to 3/4",
        "music": "spin whirr + lock chime",
        "spatial": "table centered",
        "voice": "none",
        "form_family": "compass",
        "vfx_family": "needle_lock",
    },
    # -------- Epic (20) --------
    {
        "name": "Stage Curtain Rise",
        "slug": "stage-curtain-rise",
        "rarity": "Epic",
        "price": 500,
        "duration_ms": 7000,
        "idea": "Velvet curtains part to reveal a mini spotlight on the avatar.",
        "model": "Layered curtain cloth, proscenium arch, and follow-spot fixture.",
        "environment": "Theater stage with audience silhouette depth.",
        "phases": ["dark stage", "curtain part", "spot find avatar", "applause swell", "bow"],
        "vfx": ["volumetric spot", "dust in beam"],
        "particles": "stage dust",
        "shaders": ["velvet cloth", "spot gobo"],
        "camera": "audience push onto stage",
        "music": "orchestra swell sting",
        "spatial": "hall reverb",
        "voice": "distant crowd cheer bed",
        "form_family": "theater",
        "vfx_family": "spot_volume",
    },
    {
        "name": "Kite Festival",
        "slug": "kite-festival",
        "rarity": "Epic",
        "price": 500,
        "duration_ms": 7500,
        "idea": "A fleet of patterned kites forms the streamer's initials in sky.",
        "model": "Multiple unique kite meshes with tails and frames.",
        "environment": "Open sky and grassy cliff.",
        "phases": ["launch", "weave formation", "initials lock", "release scatter"],
        "vfx": ["wind trails", "sun flare justified once"],
        "particles": "grass seeds in wind",
        "shaders": ["fabric kite", "sky gradient"],
        "camera": "drone-like rise",
        "music": "festival drums light",
        "spatial": "open air",
        "voice": "none",
        "form_family": "kites",
        "vfx_family": "wind_trails",
    },
    {
        "name": "Clockwork Bouquet",
        "slug": "clockwork-bouquet",
        "rarity": "Epic",
        "price": 1000,
        "duration_ms": 8000,
        "idea": "Mechanical flowers bloom on winding stems synchronized to a melody.",
        "model": "Gear-petaled flowers with winding keys and stems.",
        "environment": "Polished brass conservatory.",
        "phases": ["keys wind", "stems rise", "petals open", "finale tick chord"],
        "vfx": ["gear motion blur", "brass gleam"],
        "particles": "tiny gear sparks (contact)",
        "shaders": ["brass", "enamel petal"],
        "camera": "orbit bloom",
        "music": "music-box to brass swell",
        "spatial": "mechanical garden",
        "voice": "none",
        "form_family": "mech_flora",
        "vfx_family": "gear_bloom",
    },
    {
        "name": "Rain Letter",
        "slug": "rain-letter",
        "rarity": "Epic",
        "price": 500,
        "duration_ms": 7200,
        "idea": "Raindrops on a window spell a short thank-you then wash away.",
        "model": "Window frame, glass, and procedural rain droplet meshes.",
        "environment": "Night apartment window (water required).",
        "phases": ["rain start", "letters form", "read hold", "wash clear"],
        "vfx": ["window streaks", "city bokeh"],
        "particles": "rain drops",
        "shaders": ["wet glass", "rain refraction"],
        "camera": "through-window dolly",
        "music": "soft rain bed + piano",
        "spatial": "window plane stereo",
        "voice": "whispered thank-you processed lightly",
        "form_family": "window_rain",
        "vfx_family": "rain_letters",
    },
    {
        "name": "Neon Arcade Dual",
        "slug": "neon-arcade-dual",
        "rarity": "Epic",
        "price": 1000,
        "duration_ms": 7000,
        "idea": "Two neon cabinets duel with light beams then high-five as pixels.",
        "model": "Two stylized arcade cabinets with CRT screens.",
        "environment": "Arcade aisle with reflective floor.",
        "phases": ["power on", "beam duel", "pixel high-five", "score pop"],
        "vfx": ["neon bloom", "pixel burst"],
        "particles": "8-bit cubes",
        "shaders": ["CRT scan", "neon tube"],
        "camera": "low aisle track",
        "music": "chiptune duel then resolve",
        "spatial": "arcade L/R cabinets",
        "voice": "pixelated VOICE FX 'GG'",
        "form_family": "arcade",
        "vfx_family": "neon_pixel",
    },
    {
        "name": "Sand Mandala",
        "slug": "sand-mandala",
        "rarity": "Epic",
        "price": 2500,
        "duration_ms": 8500,
        "idea": "Colored sands assemble a mandala then dissolve in a respectful sweep.",
        "model": "Layered sand piles morphing into radial patterns.",
        "environment": "Monastery floor with soft daylight.",
        "phases": ["pour grains", "pattern assemble", "hold sacred", "sweep dissolve"],
        "vfx": ["grain flow", "color dust"],
        "particles": "sand grains",
        "shaders": ["sand grain", "floor stone"],
        "camera": "overhead to slight angle",
        "music": "singing bowls",
        "spatial": "temple quiet",
        "voice": "none",
        "form_family": "sand_art",
        "vfx_family": "sand_flow",
    },
    {
        "name": "Holo Ticket",
        "slug": "holo-ticket",
        "rarity": "Epic",
        "price": 1000,
        "duration_ms": 6500,
        "idea": "A holographic concert ticket unfolds into a mini stage for 3 seconds.",
        "model": "Ticket card morphing into miniature stage geometry.",
        "environment": "Concert fog light shafts (fog not fire).",
        "phases": ["ticket float", "hologram scan", "stage unfold", "encore flash"],
        "vfx": ["hologram scanlines", "fog shafts"],
        "particles": "confetti light",
        "shaders": ["holo foil", "scan"],
        "camera": "ticket hero then stage wide",
        "music": "crowd swell sting",
        "spatial": "arena-ish short",
        "voice": "announcer 'Admit One' FX",
        "form_family": "ticket_holo",
        "vfx_family": "hologram",
    },
    {
        "name": "Ice Sculpture Toast",
        "slug": "ice-sculpture-toast",
        "rarity": "Epic",
        "price": 2500,
        "duration_ms": 7800,
        "idea": "An ice sculpture of two glasses clinks and refracts a rainbow toast.",
        "model": "Carved ice goblets with internal refraction paths.",
        "environment": "Cold banquet table.",
        "phases": ["sculpt reveal", "clink", "rainbow refract", "frost settle"],
        "vfx": ["ice caustics", "frost bloom"],
        "particles": "frost crystals",
        "shaders": ["ice volume", "frost"],
        "camera": "clink close-up",
        "music": "glass clink chord",
        "spatial": "banquet near",
        "voice": "none",
        "form_family": "ice_carve",
        "vfx_family": "ice_caustic",
    },
    {
        "name": "Train of Thanks",
        "slug": "train-of-thanks",
        "rarity": "Epic",
        "price": 500,
        "duration_ms": 8000,
        "idea": "A miniature train delivers cars labeled with chat emotes to the streamer.",
        "model": "Locomotive and three unique cargo cars on a loop track.",
        "environment": "Tabletop diorama landscape.",
        "phases": ["depart", "pass cars", "unload gifts", "whistle bow"],
        "vfx": ["steam puff (train steam only)", "sparks on rails"],
        "particles": "steam puffs",
        "shaders": ["painted metal", "wood cars"],
        "camera": "tracking along track",
        "music": "playful march",
        "spatial": "diorama stereo along track",
        "voice": "whistle FX",
        "form_family": "train_diorama",
        "vfx_family": "train_steam",
    },
    {
        "name": "Prism Parade",
        "slug": "prism-parade",
        "rarity": "Epic",
        "price": 1000,
        "duration_ms": 7000,
        "idea": "A parade of floating prisms splits white light into a color ribbon path.",
        "model": "Multiple unique prism solids with different cut angles.",
        "environment": "White void with single hard key light.",
        "phases": ["prism enter", "split beam", "ribbon path", "recombine white"],
        "vfx": ["spectral split", "beam ribbons"],
        "particles": "spectral motes",
        "shaders": ["dispersion glass"],
        "camera": "beam-aligned tracking",
        "music": "spectral arpeggio",
        "spatial": "beam-following pan",
        "voice": "none",
        "form_family": "prisms",
        "vfx_family": "dispersion",
    },
    {
        "name": "Garden Gate",
        "slug": "garden-gate",
        "rarity": "Epic",
        "price": 2500,
        "duration_ms": 8200,
        "idea": "An iron garden gate opens onto a sudden bloom path to the avatar.",
        "model": "Wrought iron gate, vines, and blooming path flowers.",
        "environment": "Overgrown garden at golden hour.",
        "phases": ["locked gate", "vine unlock", "open", "bloom path", "arrive"],
        "vfx": ["petal burst", "golden godrays"],
        "particles": "petals",
        "shaders": ["iron rust", "petal SSS"],
        "camera": "walk-through POV",
        "music": "pastoral strings",
        "spatial": "outdoor garden",
        "voice": "none",
        "form_family": "garden_gate",
        "vfx_family": "petal_path",
    },
    {
        "name": "Typewriter Love",
        "slug": "typewriter-love",
        "rarity": "Epic",
        "price": 500,
        "duration_ms": 7500,
        "idea": "A typewriter types a personalized line that lifts off the page as 3D letters.",
        "model": "Vintage typewriter with flying glyph meshes.",
        "environment": "Writer's desk night lamp.",
        "phases": ["keys strike", "line forms", "letters lift", "orbit avatar"],
        "vfx": ["ink transfer", "letter trails"],
        "particles": "ink mist",
        "shaders": ["metal typewriter", "paper"],
        "camera": "desk macro then lift",
        "music": "type rhythm + warm pad",
        "spatial": "desk then lift space",
        "voice": "typed letters as rhythmic clicks",
        "form_family": "typewriter",
        "vfx_family": "flying_type",
    },
    {
        "name": "Surfboard Salute",
        "slug": "surfboard-salute",
        "rarity": "Epic",
        "price": 1000,
        "duration_ms": 7000,
        "idea": "A surfboard rides a stylized wave and plants a crest salute.",
        "model": "Custom board with unique lamination and wave ribbon mesh.",
        "environment": "Ocean horizon (water required).",
        "phases": ["wave rise", "ride", "crest salute", "exit splash"],
        "vfx": ["wave foam", "splash"],
        "particles": "foam spray",
        "shaders": ["wet board", "ocean SSS"],
        "camera": "wave chase",
        "music": "surf rock sting original",
        "spatial": "ocean wide",
        "voice": "none",
        "form_family": "surf",
        "vfx_family": "wave_foam",
    },
    {
        "name": "Balloon Orchestra",
        "slug": "balloon-orchestra",
        "rarity": "Epic",
        "price": 2500,
        "duration_ms": 8000,
        "idea": "Colored balloons inflate into instrument shapes and play a chord.",
        "model": "Balloon instruments: tuba, violin, drum approximations.",
        "environment": "Festive hall.",
        "phases": ["inflate", "shape instruments", "play chord", "release float"],
        "vfx": ["stretch latex", "sound-visual rings"],
        "particles": "confetti stars",
        "shaders": ["latex sheen"],
        "camera": "orchestra wide then close",
        "music": "balloon-like squeak orchestra joke resolve",
        "spatial": "hall instruments L/C/R",
        "voice": "none",
        "form_family": "balloon_instr",
        "vfx_family": "sound_rings",
    },
    {
        "name": "Chess Sacrifice",
        "slug": "chess-sacrifice",
        "rarity": "Epic",
        "price": 1000,
        "duration_ms": 7600,
        "idea": "A chess piece sacrifices itself to crown the recipient's king.",
        "model": "Stylized chess set with unique piece silhouettes.",
        "environment": "Marble board with dramatic key.",
        "phases": ["approach", "sacrifice move", "crown", "board glow"],
        "vfx": ["move trails", "crown light"],
        "particles": "marble dust",
        "shaders": ["marble", "ebony/ivory"],
        "camera": "board diagonal drama",
        "music": "tense then resolve chord",
        "spatial": "board plane",
        "voice": "none",
        "form_family": "chess",
        "vfx_family": "piece_trails",
    },
    {
        "name": "Meteor Postcard",
        "slug": "meteor-postcard",
        "rarity": "Epic",
        "price": 2500,
        "duration_ms": 7000,
        "idea": "A postcard rides a gentle meteor trail and lands as a stamped memory.",
        "model": "Postcard card and stylized meteor core (no destructive fire).",
        "environment": "Night sky over quiet town.",
        "phases": ["sky enter", "trail write", "postcard land", "stamp"],
        "vfx": ["meteor trail (plasma glow, not flame burst)", "stamp flash"],
        "particles": "trail sparks",
        "shaders": ["card paper", "trail additive"],
        "camera": "sky chase to desk land",
        "music": "wistful synth",
        "spatial": "sky to desk transition",
        "voice": "none",
        "form_family": "postcard",
        "vfx_family": "meteor_trail",
    },
    {
        "name": "Mirror Duet",
        "slug": "mirror-duet",
        "rarity": "Epic",
        "price": 500,
        "duration_ms": 7200,
        "idea": "A freestanding mirror shows the streamer and viewer dancing a short sync.",
        "model": "Ornate mirror frame with dual silhouette proxies.",
        "environment": "Ballroom soft light.",
        "phases": ["mirror reveal", "silhouettes sync", "step sequence", "fade smile"],
        "vfx": ["mirror ripples", "sync sparks"],
        "particles": "glitter dust",
        "shaders": ["mirror glass", "gold frame"],
        "camera": "front mirror then side",
        "music": "waltz phrase",
        "spatial": "ballroom",
        "voice": "none",
        "form_family": "mirror",
        "vfx_family": "mirror_ripple",
    },
    {
        "name": "Pottery Spin",
        "slug": "pottery-spin",
        "rarity": "Epic",
        "price": 500,
        "duration_ms": 7800,
        "idea": "Clay on a wheel rises into a vessel that paints itself with viewer color.",
        "model": "Wheel, clay body morph, glaze paint strokes.",
        "environment": "Ceramic studio window light.",
        "phases": ["lump", "rise form", "paint glaze", "fire kiln glow (story fire, contained)"],
        "vfx": ["wheel blur", "kiln glow fire only in kiln"],
        "particles": "clay flecks",
        "shaders": ["wet clay", "glaze"],
        "camera": "wheel macro",
        "music": "wheel rhythm + soft flute",
        "spatial": "studio near",
        "voice": "none",
        "form_family": "pottery",
        "vfx_family": "kiln_glow",
    },
    {
        "name": "Drone Heartbeat",
        "slug": "drone-heartbeat",
        "rarity": "Epic",
        "price": 1000,
        "duration_ms": 7000,
        "idea": "A tiny drone draws a heart path in LED light then lands a gift crate.",
        "model": "Quadcopter with LED strips and mini crate.",
        "environment": "Night rooftop.",
        "phases": ["launch", "LED heart draw", "crate drop", "land"],
        "vfx": ["LED light paint", "prop wash dust"],
        "particles": "dust wash",
        "shaders": ["matte drone", "LED emissive"],
        "camera": "follow drone",
        "music": "heartbeat pulse synth",
        "spatial": "rooftop open",
        "voice": "none",
        "form_family": "drone",
        "vfx_family": "led_paint",
    },
    {
        "name": "Quilt Embrace",
        "slug": "quilt-embrace",
        "rarity": "Epic",
        "price": 2500,
        "duration_ms": 8000,
        "idea": "Patchwork squares fly in and assemble a quilt that wraps the avatar.",
        "model": "Unique fabric patches with different patterns assembling a quilt.",
        "environment": "Cozy loft with afternoon light.",
        "phases": ["patches fly", "assemble", "wrap", "warm settle"],
        "vfx": ["stitch light", "fabric fluff"],
        "particles": "thread ends",
        "shaders": ["fabric weave variety"],
        "camera": "assemble overhead then wrap orbit",
        "music": "warm acoustic",
        "spatial": "cozy indoor",
        "voice": "none",
        "form_family": "quilt",
        "vfx_family": "stitch_light",
    },
    # -------- Legendary (20) --------
    {
        "name": "Opera Mask Reveal",
        "slug": "opera-mask-reveal",
        "rarity": "Legendary",
        "price": 5000,
        "duration_ms": 11000,
        "idea": "A masked figure steps from shadow, removes the mask, and gifts a rose of light.",
        "model": "Character bust with ornate mask, cloak, and light-rose prop; simple facial rig.",
        "environment": "Grand opera box with velvet and gold.",
        "phases": ["shadow enter", "mask remove", "eye contact", "rose gift", "bow exit"],
        "vfx": ["velvet dust", "rose light petals"],
        "particles": "light petals",
        "shaders": ["velvet", "gold leaf", "skin SSS"],
        "camera": "cinematic profile to frontal close-up",
        "music": "opera motif original (non-copyright)",
        "spatial": "hall depth",
        "voice": "soft sung vowel FX (original)",
        "form_family": "character_mask",
        "vfx_family": "rose_light",
    },
    {
        "name": "Library of Echoes",
        "slug": "library-of-echoes",
        "rarity": "Legendary",
        "price": 10000,
        "duration_ms": 12000,
        "idea": "Books fly from shelves forming a spiral tower that opens a portal of memories.",
        "model": "Hundreds of unique book covers (procedural titles) and spiral architecture.",
        "environment": "Infinite library atrium.",
        "phases": ["quiet shelves", "books lift", "spiral form", "portal open", "memory flicker", "close"],
        "vfx": ["page flocks", "portal refraction"],
        "particles": "paper flocks",
        "shaders": ["leather/cloth books", "portal glass"],
        "camera": "crane up spiral",
        "music": "choir pad + soft percussion",
        "spatial": "atrium reverb",
        "voice": "layered whisper echoes (non-speech)",
        "form_family": "library",
        "vfx_family": "book_portal",
    },
    {
        "name": "Stormglass Captain",
        "slug": "stormglass-captain",
        "rarity": "Legendary",
        "price": 10000,
        "duration_ms": 11500,
        "idea": "A captain inside a storm glass bottle steadies the seas for the stream.",
        "model": "Ship-in-bottle with captain character silhouette and storm fluid.",
        "environment": "Desk that becomes stormy sea (water + controlled lightning inside glass).",
        "phases": ["calm bottle", "storm brew", "lightning inside glass", "captain steadies", "clear skies"],
        "vfx": ["storm water", "contained lightning", "glass fog"],
        "particles": "salt spray inside",
        "shaders": ["stormglass", "wood ship"],
        "camera": "macro bottle then heroic tilt",
        "music": "sea shanty instrumental original",
        "spatial": "inside bottle muffling then clear",
        "voice": "captain 'Steady!' voice FX",
        "form_family": "ship_bottle",
        "vfx_family": "contained_storm",
    },
    {
        "name": "Ballet of Sparks",
        "slug": "ballet-of-sparks",
        "rarity": "Legendary",
        "price": 5000,
        "duration_ms": 11000,
        "idea": "Two dancers of light perform a pas de deux ending in a shared constellation.",
        "model": "Two stylized dancer mannequins with cloth and light trails; simple IK.",
        "environment": "Dark stage with reflective floor.",
        "phases": ["enter opposite", "approach", "lift", "spin trails", "constellation lock"],
        "vfx": ["light body trails", "floor reflections"],
        "particles": "spark ballet (non-fire glitter)",
        "shaders": ["emissive body", "cloth"],
        "camera": "dance cinema coverage (3 angles cut)",
        "music": "ballet piano original",
        "spatial": "stage stereo dance positions",
        "voice": "none",
        "form_family": "dancers",
        "vfx_family": "light_trails",
    },
    {
        "name": "Forge of Kindness",
        "slug": "forge-of-kindness",
        "rarity": "Legendary",
        "price": 25000,
        "duration_ms": 12500,
        "idea": "A blacksmith forges a heart-shaped charm; fire only in forge hearth as required.",
        "model": "Blacksmith character arms, anvil, hammer, charm; forge hearth.",
        "environment": "Stone forge workshop.",
        "phases": ["heat metal (forge fire)", "hammer beats", "quench steam", "present charm", "glow gift"],
        "vfx": ["forge fire", "hammer sparks", "quench steam"],
        "particles": "forge sparks",
        "shaders": ["hot metal", "stone", "leather apron"],
        "camera": "hammer impact cuts then gift present",
        "music": "hammer rhythm to warm theme",
        "spatial": "workshop industrial",
        "voice": "blacksmith grunt effort FX",
        "form_family": "forge",
        "vfx_family": "forge_fire",
    },
    {
        "name": "Observatory Wish",
        "slug": "observatory-wish",
        "rarity": "Legendary",
        "price": 10000,
        "duration_ms": 12000,
        "idea": "A dome observatory opens; a telescope finds a new star named for the viewer.",
        "model": "Observatory dome, telescope, starfield projection.",
        "environment": "Mountain night observatory.",
        "phases": ["dome open", "telescope slew", "star find", "nameplate appear", "sky bloom"],
        "vfx": ["dome slit light", "star bloom"],
        "particles": "stardust",
        "shaders": ["metal dome", "lens glass"],
        "camera": "exterior dome then through eyepiece",
        "music": "celestial orchestra sting",
        "spatial": "mountain night open",
        "voice": "soft 'New star catalogued' AI VO FX",
        "form_family": "observatory",
        "vfx_family": "star_find",
    },
    {
        "name": "Paper City Dawn",
        "slug": "paper-city-dawn",
        "rarity": "Legendary",
        "price": 5000,
        "duration_ms": 11500,
        "idea": "A folded paper city rises and sunrise paints windows one by one.",
        "model": "Modular paper buildings with unique silhouettes.",
        "environment": "Paper diorama table becoming dawn sky.",
        "phases": ["flat paper", "city unfold", "dawn paint", "windows light", "bird fly"],
        "vfx": ["sunrise gradient", "window lights"],
        "particles": "paper birds",
        "shaders": ["paper buildings", "dawn sky"],
        "camera": "city crane",
        "music": "dawn ambient + soft choir",
        "spatial": "city wide then intimate street",
        "voice": "none",
        "form_family": "paper_city",
        "vfx_family": "dawn_windows",
    },
    {
        "name": "Dragonfly Courier",
        "slug": "dragonfly-courier",
        "rarity": "Legendary",
        "price": 10000,
        "duration_ms": 11000,
        "idea": "A giant jeweled dragonfly delivers a crystal message orb to the streamer.",
        "model": "Dragonfly with iridescent wings, articulated body, orb payload.",
        "environment": "Wetland morning (water reflections).",
        "phases": ["distant approach", "wing beats", "orb handoff", "circle exit"],
        "vfx": ["wing iridescence", "orb glow"],
        "particles": "morning mist",
        "shaders": ["chitin", "thin-film wings"],
        "camera": "aerial chase",
        "music": "light wing rhythm",
        "spatial": "wetland open",
        "voice": "none",
        "form_family": "dragonfly",
        "vfx_family": "wing_iridescence",
    },
    {
        "name": "Cathedral of Quiet",
        "slug": "cathedral-of-quiet",
        "rarity": "Legendary",
        "price": 25000,
        "duration_ms": 13000,
        "idea": "Stained glass reforms into a quiet cathedral aisle that ends in a gift altar.",
        "model": "Stained glass panels, columns, altar gift.",
        "environment": "Sacred interior with godrays.",
        "phases": ["shards float", "assemble windows", "aisle form", "walk light", "altar gift"],
        "vfx": ["stained light shafts", "dust in beams"],
        "particles": "sacred dust",
        "shaders": ["stained glass", "stone"],
        "camera": "aisle processional",
        "music": "organ soft original",
        "spatial": "cathedral reverb",
        "voice": "choir pad only",
        "form_family": "cathedral",
        "vfx_family": "stained_shafts",
    },
    {
        "name": "Mecha Origami Crane",
        "slug": "mecha-origami-crane",
        "rarity": "Legendary",
        "price": 10000,
        "duration_ms": 12000,
        "idea": "An origami crane unfolds into a gentle mecha that kneels and offers a gift.",
        "model": "Crane-to-mecha transformation mesh with hinges; simple mechanical rig.",
        "environment": "Rooftop at dusk.",
        "phases": ["paper crane", "panel unfold", "mecha stand", "kneel offer", "bow"],
        "vfx": ["panel light seams", "servo sparks (contact)"],
        "particles": "paper to metal transition flecks",
        "shaders": ["paper then metal plates"],
        "camera": "transformation hero orbit",
        "music": "hybrid acoustic-electronic",
        "spatial": "rooftop city",
        "voice": "servo voice chirp",
        "form_family": "mecha_crane",
        "vfx_family": "transform_seams",
    },
    {
        "name": "Underwater Ballroom",
        "slug": "underwater-ballroom",
        "rarity": "Legendary",
        "price": 25000,
        "duration_ms": 12500,
        "idea": "A flooded ballroom hosts a waltz of jellyfish lanterns (water required).",
        "model": "Ballroom ruins, jellyfish lantern creatures, dance floor.",
        "environment": "Underwater palace.",
        "phases": ["descend", "lanterns arrive", "waltz circle", "gift pearl", "ascend light"],
        "vfx": ["caustics", "bubble columns"],
        "particles": "bubbles",
        "shaders": ["wet marble", "biolume jellyfish"],
        "camera": "underwater crane dance",
        "music": "muffled waltz",
        "spatial": "underwater muffled hall",
        "voice": "none",
        "form_family": "underwater_ball",
        "vfx_family": "jellyfish_waltz",
    },
    {
        "name": "Painter's Storm",
        "slug": "painters-storm",
        "rarity": "Legendary",
        "price": 5000,
        "duration_ms": 11000,
        "idea": "Brush strokes paint a storm that clears into a portrait of gratitude.",
        "model": "Giant brush, paint ribbons becoming landscape then portrait planes.",
        "environment": "Artist loft that becomes painted world.",
        "phases": ["blank canvas", "storm strokes", "lightning paint flash (painted, not real)", "clear portrait", "frame"],
        "vfx": ["paint ribbons", "painted lightning"],
        "particles": "paint flecks",
        "shaders": ["wet paint", "canvas"],
        "camera": "brush POV then reveal",
        "music": "storm percussion to soft resolve",
        "spatial": "studio to world",
        "voice": "none",
        "form_family": "paint_world",
        "vfx_family": "paint_storm",
    },
    {
        "name": "Timekeeper's Gift",
        "slug": "timekeepers-gift",
        "rarity": "Legendary",
        "price": 10000,
        "duration_ms": 12000,
        "idea": "A grandfather clock opens; gears rearrange into a pocket-watch gift.",
        "model": "Grandfather clock interior, gears, pocket watch finale.",
        "environment": "Antique hall.",
        "phases": ["chime", "door open", "gear rearrange", "slow-mo assemble", "present watch"],
        "vfx": ["time freeze dust", "gear trails"],
        "particles": "clock dust",
        "shaders": ["wood lacquer", "brass gears"],
        "camera": "interior macro with slow-mo",
        "music": "chimes + ticking motif",
        "spatial": "hall clock resonance",
        "voice": "clock tick as metronome VO",
        "form_family": "clock",
        "vfx_family": "time_freeze",
    },
    {
        "name": "Foxfire Path",
        "slug": "foxfire-path",
        "rarity": "Legendary",
        "price": 25000,
        "duration_ms": 11500,
        "idea": "A spirit fox of soft foxfire leads a path of mushrooms to a hidden shrine.",
        "model": "Stylized fox character with simple spine rig; mushroom path; shrine.",
        "environment": "Night forest (foxfire glow — not destructive fire).",
        "phases": ["fox appear", "path light", "run ahead", "shrine reveal", "gift leave"],
        "vfx": ["foxfire glow", "mushroom light"],
        "particles": "spore lights",
        "shaders": ["fur stylized", "biolume mushrooms"],
        "camera": "follow fox through trees",
        "music": "folk flute night",
        "spatial": "forest depth",
        "voice": "fox soft chuff FX",
        "form_family": "spirit_fox",
        "vfx_family": "foxfire",
    },
    {
        "name": "Glassblower's Heart",
        "slug": "glassblowers-heart",
        "rarity": "Legendary",
        "price": 10000,
        "duration_ms": 12000,
        "idea": "A glassblower shapes molten glass into a transparent heart (fire at glory hole only).",
        "model": "Blowpipe, molten gather, heart vessel; studio bench.",
        "environment": "Glass studio with glory hole fire.",
        "phases": ["gather melt", "blow shape", "marver", "anneal glow", "present"],
        "vfx": ["glory hole fire", "heat shimmer", "glass stretch"],
        "particles": "heat motes",
        "shaders": ["molten glass", "cooled glass"],
        "camera": "hands and gather close-ups",
        "music": "warm drones + glass tones",
        "spatial": "studio industrial warm",
        "voice": "breath blow FX",
        "form_family": "glassblow",
        "vfx_family": "glory_fire",
    },
    {
        "name": "Sky Whale Passage",
        "slug": "sky-whale-passage",
        "rarity": "Legendary",
        "price": 25000,
        "duration_ms": 13000,
        "idea": "A gentle sky whale passes overhead trailing gardens that rain seeds of light.",
        "model": "Sky whale creature with garden terraces on back; seed pods.",
        "environment": "Cloud ocean at golden hour.",
        "phases": ["distant silhouette", "pass overhead", "seed rain", "avatar bloom", "whale exit"],
        "vfx": ["cloud wake", "seed light rain"],
        "particles": "light seeds",
        "shaders": ["whale skin SSS", "cloud volume proxy"],
        "camera": "epic under-whale crane",
        "music": "vast soft choir",
        "spatial": "sky immense",
        "voice": "whale song-like FX (original)",
        "form_family": "sky_whale",
        "vfx_family": "seed_rain",
    },
    {
        "name": "Samurai Ink Slash",
        "slug": "samurai-ink-slash",
        "rarity": "Legendary",
        "price": 5000,
        "duration_ms": 10000,
        "idea": "A calligrapher-samurai draws a single ink slash that becomes a protective circle.",
        "model": "Character with brush-sword hybrid; ink slash ribbons.",
        "environment": "Dojo with paper screens.",
        "phases": ["stance", "draw slash", "ink hang in air", "circle close", "protect pulse"],
        "vfx": ["ink slash", "screen flutter"],
        "particles": "ink mist",
        "shaders": ["ink", "wood dojo"],
        "camera": "dramatic slash follow",
        "music": "taiko + silence beat",
        "spatial": "dojo",
        "voice": "kiai short original",
        "form_family": "ink_samurai",
        "vfx_family": "ink_slash",
    },
    {
        "name": "Carousel Confession",
        "slug": "carousel-confession",
        "rarity": "Legendary",
        "price": 10000,
        "duration_ms": 12000,
        "idea": "A night carousel starts; each horse carries a memory lantern to the streamer.",
        "model": "Carousel canopy, unique horses, lanterns.",
        "environment": "Fairground night.",
        "phases": ["still", "start spin", "lanterns light", "horse bow", "gift drop"],
        "vfx": ["fair lights", "motion blur horses"],
        "particles": "fair sparkles",
        "shaders": ["painted wood", "bulb emissive"],
        "camera": "on-carousel then wide",
        "music": "carousel waltz original",
        "spatial": "spinning fair",
        "voice": "none",
        "form_family": "carousel",
        "vfx_family": "fair_lights",
    },
    {
        "name": "Alpine Beacon",
        "slug": "alpine-beacon",
        "rarity": "Legendary",
        "price": 25000,
        "duration_ms": 11500,
        "idea": "Mountaineers light a beacon network across peaks spelling THANKS.",
        "model": "Peaks, beacon towers, light beams between them.",
        "environment": "Alpine night (beacon fire contained in braziers).",
        "phases": ["dark peaks", "first beacon fire", "relay lights", "THANKS beams", "aurora tip"],
        "vfx": ["beacon fire", "beam network", "light aurora"],
        "particles": "snow wind",
        "shaders": ["snow rock", "fire emissive"],
        "camera": "aerial peak tour",
        "music": "alpine horns soft",
        "spatial": "mountain vast",
        "voice": "distant call FX",
        "form_family": "alpine",
        "vfx_family": "beacon_network",
    },
    {
        "name": "Violin Aurora",
        "slug": "violin-aurora",
        "rarity": "Legendary",
        "price": 5000,
        "duration_ms": 11000,
        "idea": "A violin bow draws aurora ribbons that form a protective canopy.",
        "model": "Violin, bow, aurora ribbon meshes.",
        "environment": "Cliff overlooking fjord.",
        "phases": ["first note", "ribbon draw", "canopy weave", "finale chord", "settle"],
        "vfx": ["aurora from bow", "note rings"],
        "particles": "note sparkles",
        "shaders": ["wood violin", "aurora additive"],
        "camera": "musician close then sky wide",
        "music": "solo violin original phrase",
        "spatial": "cliff open air",
        "voice": "none",
        "form_family": "violin",
        "vfx_family": "bow_aurora",
    },
    # -------- Mythic (20) --------
    {
        "name": "Worldfold Letter",
        "slug": "worldfold-letter",
        "rarity": "Mythic",
        "price": 50000,
        "duration_ms": 16000,
        "idea": "Reality folds like paper; a letter world opens where streamer and viewers meet.",
        "model": "Folding terrain panels, letter architecture, avatar proxies.",
        "environment": "Transforms from chat UI into folded paper world then back.",
        "phases": ["UI fold", "world open", "paths meet", "shared plaza", "refold return"],
        "vfx": ["world fold seams", "UI particle dissolve"],
        "particles": "fold sparks",
        "shaders": ["paper world", "UI emissive"],
        "camera": "impossible fold transitions",
        "music": "transforming motif A->B->A",
        "spatial": "scene-morph spatial remap",
        "voice": "AI narrator soft line",
        "form_family": "worldfold",
        "vfx_family": "reality_fold",
    },
    {
        "name": "Tide of Voices",
        "slug": "tide-of-voices",
        "rarity": "Mythic",
        "price": 100000,
        "duration_ms": 17000,
        "idea": "Viewer chat becomes a luminous tide that the streamer surfs safely to shore.",
        "model": "Wave made of glyph tiles; surfboard of light; shoreline stage.",
        "environment": "Scene transforms from chatroom to ocean of text (water metaphor).",
        "phases": ["glyphs rise", "tide form", "surf ride", "shore arrive", "glyphs become flowers"],
        "vfx": ["glyph tide", "foam of characters"],
        "particles": "floating glyphs",
        "shaders": ["glyph emissive", "shore sand"],
        "camera": "surf chase multi-scene",
        "music": "dynamic tide intensity",
        "spatial": "ocean of voices",
        "voice": "chorus of processed viewer snippets (privacy-safe tones)",
        "form_family": "glyph_tide",
        "vfx_family": "chat_ocean",
    },
    {
        "name": "Twin Eclipse",
        "slug": "twin-eclipse",
        "rarity": "Mythic",
        "price": 250000,
        "duration_ms": 18000,
        "idea": "Two suns eclipse; during totality avatars of streamer and top gifter dance.",
        "model": "Twin suns, lunar occluders, avatar dancers, corona.",
        "environment": "Celestial arena that darkens then returns.",
        "phases": ["day twin suns", "approach eclipse", "totality dance", "corona gift", "day return"],
        "vfx": ["corona", "shadow bands"],
        "particles": "solar dust",
        "shaders": ["sun volume", "corona additive"],
        "camera": "celestial epic coverage",
        "music": "eclipse choir",
        "spatial": "sky dome",
        "voice": "none",
        "form_family": "eclipse",
        "vfx_family": "corona",
    },
    {
        "name": "Root Network",
        "slug": "root-network",
        "rarity": "Mythic",
        "price": 50000,
        "duration_ms": 16000,
        "idea": "Tree roots connect every viewer node underground then bloom a shared canopy.",
        "model": "Root network geometry, node lights, canopy tree.",
        "environment": "Underground to forest canopy transform.",
        "phases": ["dig view", "roots connect", "pulse sync", "surface bloom", "canopy gift"],
        "vfx": ["root pulse light", "leaf burst"],
        "particles": "soil motes then pollen",
        "shaders": ["root bark", "leaf SSS"],
        "camera": "underground travel then canopy rise",
        "music": "heartbeat to canopy swell",
        "spatial": "underground muffling to open canopy",
        "voice": "AI 'We are connected' FX",
        "form_family": "roots",
        "vfx_family": "network_pulse",
    },
    {
        "name": "Mirror Ocean Trial",
        "slug": "mirror-ocean-trial",
        "rarity": "Mythic",
        "price": 100000,
        "duration_ms": 17500,
        "idea": "Streamer walks a mirror ocean; reflections become allies that lift a gift island.",
        "model": "Mirror ocean plane, reflection allies, rising island.",
        "environment": "Infinite mirror sea (water required).",
        "phases": ["step onto mirror", "reflections awaken", "walk trial", "island rise", "gift shrine"],
        "vfx": ["mirror fractures heal", "island birth"],
        "particles": "mirror shards that rejoin",
        "shaders": ["perfect mirror", "island rock"],
        "camera": "low across mirror then island crane",
        "music": "trial tension to triumph",
        "spatial": "infinite reflections",
        "voice": "reflection whispers",
        "form_family": "mirror_ocean",
        "vfx_family": "mirror_allies",
    },
    {
        "name": "Clockwork Cosmos",
        "slug": "clockwork-cosmos",
        "rarity": "Mythic",
        "price": 250000,
        "duration_ms": 18000,
        "idea": "Planets on brass arms realign; a cosmic key winds the stream's luck.",
        "model": "Orrery with unique planets, brass arms, cosmic key.",
        "environment": "Void workshop becoming cosmos.",
        "phases": ["still orrery", "arms move", "planets align", "key wind", "luck aurora"],
        "vfx": ["orbital trails", "alignment beam"],
        "particles": "cosmic dust",
        "shaders": ["brass", "planet materials unique"],
        "camera": "orrery macro to cosmos pullback",
        "music": "mechanical cosmos theme",
        "spatial": "workshop to void",
        "voice": "none",
        "form_family": "orrery",
        "vfx_family": "orbital_align",
    },
    {
        "name": "Labyrinth of Thanks",
        "slug": "labyrinth-of-thanks",
        "rarity": "Mythic",
        "price": 50000,
        "duration_ms": 17000,
        "idea": "A living labyrinth rearranges so every viewer path leads to one center gift.",
        "model": "Moving hedge/wall modules, center pedestal.",
        "environment": "Labyrinth that reconfigures live.",
        "phases": ["enter maze", "walls shift", "viewer markers move", "center open", "gift rise"],
        "vfx": ["wall shift dust", "path glow"],
        "particles": "hedge leaves",
        "shaders": ["hedge", "stone"],
        "camera": "top-down then POV race",
        "music": "puzzle motif resolving",
        "spatial": "maze corridors",
        "voice": "AI guide hints",
        "form_family": "labyrinth",
        "vfx_family": "shifting_walls",
    },
    {
        "name": "Phoenix of Paper",
        "slug": "phoenix-of-paper",
        "rarity": "Mythic",
        "price": 500000,
        "duration_ms": 19000,
        "idea": "A paper phoenix burns only as glowing ink edges, reforms, and crowns the streamer.",
        "model": "Paper phoenix with wing layers; ash is paper confetti not dirty smoke.",
        "environment": "Sky temple transform.",
        "phases": ["paper bird", "ink-edge burn (stylized fire)", "ash confetti", "reform", "crown"],
        "vfx": ["stylized edge fire", "paper ash", "reform light"],
        "particles": "paper ash",
        "shaders": ["paper layers", "ink fire edge"],
        "camera": "mythic flight coverage",
        "music": "rebirth theme",
        "spatial": "sky temple",
        "voice": "phoenix cry original",
        "form_family": "paper_phoenix",
        "vfx_family": "ink_fire_rebirth",
    },
    {
        "name": "Quantum Atelier",
        "slug": "quantum-atelier",
        "rarity": "Mythic",
        "price": 100000,
        "duration_ms": 16000,
        "idea": "An atelier where every brushstroke exists in multiple timelines until viewers vote one.",
        "model": "Studio with split timeline canvases and collapsing choice.",
        "environment": "Splits into parallel ateliers then collapses.",
        "phases": ["split studio", "parallel paint", "viewer choice pulse", "collapse", "final art gift"],
        "vfx": ["timeline ghosts", "collapse flash"],
        "particles": "probability sparks",
        "shaders": ["ghost overlays", "final paint"],
        "camera": "split-screen cinematic then merge",
        "music": "layered motifs collapsing to one",
        "spatial": "multi-room then single",
        "voice": "AI 'Choose a timeline'",
        "form_family": "quantum_studio",
        "vfx_family": "timeline_collapse",
    },
    {
        "name": "Serpent of Rivers",
        "slug": "serpent-of-rivers",
        "rarity": "Mythic",
        "price": 250000,
        "duration_ms": 18000,
        "idea": "River serpent of pure water coils the map and leaves fertile valleys as gifts.",
        "model": "Long water serpent creature; terrain morph valleys.",
        "environment": "Map world that reshapes (water required).",
        "phases": ["serpent rise", "coil map", "valleys form", "villages light", "serpent rest"],
        "vfx": ["water body", "terrain morph"],
        "particles": "spray mist",
        "shaders": ["water serpent", "terrain"],
        "camera": "map god-view to valley intimate",
        "music": "mythic river theme",
        "spatial": "world scale",
        "voice": "serpent rumble",
        "form_family": "river_serpent",
        "vfx_family": "terrain_water",
    },
    {
        "name": "Archive of First Lights",
        "slug": "archive-of-first-lights",
        "rarity": "Mythic",
        "price": 50000,
        "duration_ms": 16500,
        "idea": "An archive vault opens drawers of first-stream moments reconstructed as dioramas.",
        "model": "Vault, drawers, multiple unique diorama scenes.",
        "environment": "Archive hall transforming drawer-to-world.",
        "phases": ["vault open", "drawer pull", "diorama grow", "moments play", "seal gift"],
        "vfx": ["memory haze", "diorama scale"],
        "particles": "archive dust",
        "shaders": ["metal vault", "diorama variety"],
        "camera": "drawer dive transitions",
        "music": "nostalgic theme",
        "spatial": "vault to memory spaces",
        "voice": "AI archivist",
        "form_family": "archive",
        "vfx_family": "diorama_grow",
    },
    {
        "name": "Thunder Tea Ceremony",
        "slug": "thunder-tea-ceremony",
        "rarity": "Mythic",
        "price": 100000,
        "duration_ms": 17000,
        "idea": "A tea ceremony where each pour summons a distant thunder that becomes soft rain of petals.",
        "model": "Tea set, tatami space, storm beyond screens; lightning only distant as ceremony beat.",
        "environment": "Tea room with storm garden.",
        "phases": ["prepare", "pour", "distant lightning", "rain petals", "share bowls"],
        "vfx": ["distant lightning", "petal rain", "steam"],
        "particles": "petals + steam",
        "shaders": ["ceramic", "tatami", "storm glass"],
        "camera": "ceremony intimate with storm cutaways",
        "music": "tea silence + thunder timing",
        "spatial": "room vs storm outdoor",
        "voice": "soft host greeting",
        "form_family": "tea_storm",
        "vfx_family": "ceremony_thunder",
    },
    {
        "name": "Constellation Circus",
        "slug": "constellation-circus",
        "rarity": "Mythic",
        "price": 250000,
        "duration_ms": 18000,
        "idea": "A circus under a living sky where acts are constellations performing for the chat.",
        "model": "Circus tent, constellation acrobat figures, ring.",
        "environment": "Tent opens to living star circus.",
        "phases": ["tent rise", "sky open", "acts perform", "finale pyramid", "gift star"],
        "vfx": ["constellation performers", "spotlight stars"],
        "particles": "stardust confetti",
        "shaders": ["tent fabric", "star bodies"],
        "camera": "circus show coverage",
        "music": "circus mythic hybrid",
        "spatial": "tent to open sky",
        "voice": "ringmaster AI",
        "form_family": "star_circus",
        "vfx_family": "constellation_acts",
    },
    {
        "name": "Greenhouse Exodus",
        "slug": "greenhouse-exodus",
        "rarity": "Mythic",
        "price": 50000,
        "duration_ms": 16000,
        "idea": "A glass greenhouse lifts into sky carrying a garden that seeds the stream overlay.",
        "model": "Greenhouse architecture, plants, sky lift cables of light.",
        "environment": "Garden to sky migration.",
        "phases": ["doors close", "lift off", "sky travel", "seed overlay", "land as HUD garden"],
        "vfx": ["glass reflections", "seed HUD"],
        "particles": "soil and petals in lift",
        "shaders": ["glasshouse", "foliage"],
        "camera": "lift epic",
        "music": "lift theme",
        "spatial": "ground to sky",
        "voice": "none",
        "form_family": "greenhouse",
        "vfx_family": "hud_seed",
    },
    {
        "name": "Mask Market Midnight",
        "slug": "mask-market-midnight",
        "rarity": "Mythic",
        "price": 100000,
        "duration_ms": 17500,
        "idea": "A night market of living masks; the perfect mask chooses the streamer.",
        "model": "Market stalls, many unique masks with micro expressions.",
        "environment": "Alley market that blooms neon then sacred quiet.",
        "phases": ["enter market", "masks awaken", "trial faces", "mask chooses", "reveal true gift"],
        "vfx": ["mask eye lights", "neon then candle"],
        "particles": "lantern ash soft",
        "shaders": ["lacquer masks", "neon wet street"],
        "camera": "market wander to intimate choose",
        "music": "market bustle to hush",
        "spatial": "crowd then quiet",
        "voice": "mask whispers",
        "form_family": "mask_market",
        "vfx_family": "living_masks",
    },
    {
        "name": "Engine of Empathy",
        "slug": "engine-of-empathy",
        "rarity": "Mythic",
        "price": 250000,
        "duration_ms": 18000,
        "idea": "A vast empathy engine converts cheers into visible warmth that shields the streamer.",
        "model": "Engine core, conduits, warmth shield dome.",
        "environment": "Machine cathedral transforming to soft shield world.",
        "phases": ["engine idle", "cheer intake", "core spin", "shield deploy", "warmth settle"],
        "vfx": ["energy conduits", "shield dome"],
        "particles": "cheer sparks",
        "shaders": ["machine metal", "warmth shield"],
        "camera": "engine interior to shield exterior",
        "music": "machine pulse to human warmth",
        "spatial": "industrial to soft",
        "voice": "AI engine status lines",
        "form_family": "empathy_engine",
        "vfx_family": "warmth_shield",
    },
    {
        "name": "Desert Library Mirage",
        "slug": "desert-library-mirage",
        "rarity": "Mythic",
        "price": 500000,
        "duration_ms": 19000,
        "idea": "A mirage library solidifies; reading a tome rewrites the desert into oasis.",
        "model": "Mirage architecture, tome, oasis morph terrain.",
        "environment": "Desert to oasis transform (water appears).",
        "phases": ["heat mirage", "library solid", "tome open", "oasis rewrite", "gift spring"],
        "vfx": ["heat shimmer", "water birth"],
        "particles": "sand then water spray",
        "shaders": ["sandstone", "water oasis"],
        "camera": "mirage approach then oasis reveal",
        "music": "desert to water theme",
        "spatial": "dry to wet acoustic",
        "voice": "librarian AI",
        "form_family": "mirage_lib",
        "vfx_family": "oasis_rewrite",
    },
    {
        "name": "Choir of Instruments",
        "slug": "choir-of-instruments",
        "rarity": "Mythic",
        "price": 100000,
        "duration_ms": 17000,
        "idea": "Abandoned instruments awaken, float, and form a choir that plays the chat's tempo.",
        "model": "Many unique instruments (violin, drums, flute, harp, horn) with simple rigs.",
        "environment": "Abandoned hall to luminous concert.",
        "phases": ["dusty hall", "instruments lift", "tune", "choir play", "finale gift score"],
        "vfx": ["sound visible ribbons", "dust to light"],
        "particles": "dust to sparkles",
        "shaders": ["aged wood/metal to restored"],
        "camera": "hall coverage concert",
        "music": "dynamic chat-tempo arrangement",
        "spatial": "full orchestra imaging",
        "voice": "none — instruments speak",
        "form_family": "instrument_choir",
        "vfx_family": "sound_ribbons",
    },
    {
        "name": "Bridge Between Streams",
        "slug": "bridge-between-streams",
        "rarity": "Mythic",
        "price": 250000,
        "duration_ms": 18000,
        "idea": "A luminous bridge builds between two live streams; avatars meet mid-span.",
        "model": "Bridge segments assembling, two stream portals, avatar proxies.",
        "environment": "Void between two live scenes.",
        "phases": ["portals open", "bridge build", "meet mid", "exchange gifts", "bridge remain as badge"],
        "vfx": ["portal frames", "bridge light"],
        "particles": "construction sparks",
        "shaders": ["light architecture"],
        "camera": "cross-bridge tracking",
        "music": "meeting theme",
        "spatial": "two rooms connected",
        "voice": "dual AI greet",
        "form_family": "stream_bridge",
        "vfx_family": "portal_bridge",
    },
    {
        "name": "Moonlit Forge Garden",
        "slug": "moonlit-forge-garden",
        "rarity": "Mythic",
        "price": 500000,
        "duration_ms": 19000,
        "idea": "A forge under moonlight grows metal flowers; fire only in forge, garden otherwise cool.",
        "model": "Moonlit forge, metal flowers with unique blooms, moon.",
        "environment": "Night garden with forge hearth.",
        "phases": ["moon rise", "forge heat", "metal flowers grow", "cool shine", "bouquet gift"],
        "vfx": ["forge fire", "moon caustics", "metal bloom"],
        "particles": "embers contained + moon dust",
        "shaders": ["hot metal cooling", "petal metal"],
        "camera": "forge to garden panorama",
        "music": "moon + hammer hybrid",
        "spatial": "garden night",
        "voice": "none",
        "form_family": "moon_forge",
        "vfx_family": "metal_flowers",
    },
    # -------- Divine (20) --------
    {
        "name": "SYLORA Genesis Spire",
        "slug": "sylora-genesis-spire",
        "rarity": "Divine",
        "price": 1000000,
        "duration_ms": 25000,
        "idea": "A multi-scene origin: void, first light, city of creators, spire gift to streamer.",
        "model": "Unique spire architecture, city modules, light being guide.",
        "environment": "Four linked scenes: void, dawn plain, creator city, spire summit.",
        "phases": ["void", "first light", "city rise", "ascent", "summit gift", "world pulse"],
        "vfx": ["genesis light", "city birth", "summit aurora"],
        "particles": "creation motes staged per scene",
        "shaders": ["unique per scene art pass"],
        "camera": "multi-scene cinematic language",
        "music": "full original suite with movements",
        "spatial": "scene-by-scene acoustic design",
        "voice": "SYLORA guide original VO",
        "form_family": "genesis_spire",
        "vfx_family": "multi_scene_genesis",
    },
    {
        "name": "Ocean of Names",
        "slug": "ocean-of-names",
        "rarity": "Divine",
        "price": 2500000,
        "duration_ms": 26000,
        "idea": "An ocean where every wave crest is a viewer name; the streamer walks a path of gratitude.",
        "model": "Name-glyph waves, path stones, horizon temple.",
        "environment": "Mythic ocean that responds to live chat density (water required).",
        "phases": ["shore", "names rise", "path form", "walk", "temple gift", "ocean calm"],
        "vfx": ["name waves", "path light", "temple beacon"],
        "particles": "name foam",
        "shaders": ["glyph water", "temple stone"],
        "camera": "epic pilgrimage coverage",
        "music": "ocean suite",
        "spatial": "vast ocean imaging",
        "voice": "name chorus processed safely",
        "form_family": "name_ocean",
        "vfx_family": "glyph_waves",
    },
    {
        "name": "Celestial Phoenix",
        "slug": "celestial-phoenix",
        "rarity": "Divine",
        "price": 1000000,
        "duration_ms": 15000,
        "idea": "A cosmic portal tears open; a gigantic celestial phoenix emerges, wings ignite into galaxies, solar feathers explode, circles the streamer, lands with a divine halo, golden fire rains, then everything explodes into stars.",
        "model": "Continuous avian loft body, layered wing/tail feather cards, beak, crest, eyes; portal + ritual temple env.",
        "environment": "Dark cosmic void with mid-sequence ritual temple reveal.",
        "phases": [
            "portal tear",
            "emergence",
            "galaxy wings",
            "solar feathers",
            "orbit streamer",
            "temple transform",
            "landing",
            "halo",
            "golden rain",
            "star burst",
        ],
        "vfx": ["portal energy", "solar fire", "magic particles", "ember trails", "energy waves", "halo bloom"],
        "particles": "solar feathers / star burst / embers / magic sparks",
        "shaders": ["gold PBR body", "galaxy/fire feathers", "emissive portal"],
        "camera": "Hollywood multi-shot: crane, orbit, dolly, zoom, handheld shake",
        "music": "original cinematic drone + portal tear + wing whoosh + choir + cry + finale",
        "spatial": "stereo spatial bed with dynamic whoosh imaging",
        "voice": "phoenix cry formant burst",
        "form_family": "celestial_phoenix",
        "vfx_family": "solar_galaxy_fire",
    },
    {
        "name": "Dream Archipelago",
        "slug": "dream-archipelago",
        "rarity": "Divine",
        "price": 1000000,
        "duration_ms": 24000,
        "idea": "Viewer dreams become islands; the streamer sails a luminous skiff collecting kindness.",
        "model": "Skiff, dream islands with unique biomes, kindness lanterns.",
        "environment": "Dream sea with biome islands.",
        "phases": ["embark", "island 1", "island 2", "island 3", "lantern net", "return gift"],
        "vfx": ["dream haze", "biome-unique VFX"],
        "particles": "dream pollen variants",
        "shaders": ["per-biome art"],
        "camera": "voyage cinematic",
        "music": "voyage suite",
        "spatial": "open dream sea",
        "voice": "dream guide AI",
        "form_family": "dream_isles",
        "vfx_family": "biome_voyage",
    },
    {
        "name": "Protocol of Dawn",
        "slug": "protocol-of-dawn",
        "rarity": "Divine",
        "price": 2500000,
        "duration_ms": 25000,
        "idea": "A living protocol visualizes SYLORA systems as luminous architecture waking at dawn.",
        "model": "Abstract architecture of API/nodes/streams as beautiful structures — not UI screenshots.",
        "environment": "Digital-physical dawn city.",
        "phases": ["dark grid", "nodes wake", "bridges form", "dawn hit", "heartbeat gift"],
        "vfx": ["node awaken", "data aurora (abstract)"],
        "particles": "packet fireflies",
        "shaders": ["luminous architecture"],
        "camera": "city-scale cinematic",
        "music": "protocol dawn suite",
        "spatial": "city network",
        "voice": "system soft VO",
        "form_family": "protocol_city",
        "vfx_family": "node_dawn",
    },
    {
        "name": "Garden Between Universes",
        "slug": "garden-between-universes",
        "rarity": "Divine",
        "price": 5000000,
        "duration_ms": 28000,
        "idea": "A garden suspended between two universes where gifts grow as living constellations.",
        "model": "Floating garden, universe orbs, constellation flora.",
        "environment": "Liminal garden with dual-sky.",
        "phases": ["arrive liminal", "universes hum", "flora constellation", "harvest gift", "dual dawn"],
        "vfx": ["dual-sky blend", "constellation flora"],
        "particles": "universe pollen",
        "shaders": ["liminal materials"],
        "camera": "impossible garden coverage",
        "music": "liminal suite",
        "spatial": "between-worlds acoustic",
        "voice": "garden keeper",
        "form_family": "liminal_garden",
        "vfx_family": "dual_universe",
    },
    {
        "name": "Emperor of Paper Suns",
        "slug": "emperor-of-paper-suns",
        "rarity": "Divine",
        "price": 10000000,
        "duration_ms": 30000,
        "idea": "A paper emperor raises a sun made of a thousand unique paper layers; ultimate premium finale.",
        "model": "Emperor character full costume, thousand-layer paper sun, court.",
        "environment": "Imperial paper palace multi-hall.",
        "phases": ["court gather", "emperor enter", "sun assemble", "light the world", "kneel gift", "fade to crest"],
        "vfx": ["paper sun ignition (light not destructive fire)", "palace gold dust"],
        "particles": "paper sun layers",
        "shaders": ["imperial art pass"],
        "camera": "royal multi-scene",
        "music": "imperial finale suite",
        "spatial": "palace halls",
        "voice": "emperor blessing original",
        "form_family": "paper_emperor",
        "vfx_family": "paper_sun",
    },
    {
        "name": "Deep Time Coral Crown",
        "slug": "deep-time-coral-crown",
        "rarity": "Divine",
        "price": 2500000,
        "duration_ms": 26000,
        "idea": "Ages of coral growth compress into a crown gifted from the deep (water required).",
        "model": "Time-lapse coral architectures, crown jewel, deep fauna silhouettes.",
        "environment": "Abyssal to sunlit reef journey.",
        "phases": ["abyss", "ages pass", "coral city", "crown form", "ascend gift"],
        "vfx": ["time-lapse growth", "abyss biolume", "sunlit caustics"],
        "particles": "marine snow",
        "shaders": ["deep SSS coral"],
        "camera": "abyss to surface pilgrimage",
        "music": "deep time suite",
        "spatial": "pressure muffling to bright reef",
        "voice": "deep whale-like FX",
        "form_family": "coral_crown",
        "vfx_family": "deep_time",
    },
    {
        "name": "Symphony of Cities",
        "slug": "symphony-of-cities",
        "rarity": "Divine",
        "price": 5000000,
        "duration_ms": 28000,
        "idea": "Five cities play as instruments; their combined skyline becomes a gift monument.",
        "model": "Five unique city kits with different architecture languages.",
        "environment": "Planet panorama with city movements.",
        "phases": ["city 1 theme", "2", "3", "4", "5", "combine monument"],
        "vfx": ["skyline light shows unique per city"],
        "particles": "city-specific",
        "shaders": ["per-city art"],
        "camera": "planetary tour",
        "music": "five-movement symphony",
        "spatial": "planetary imaging",
        "voice": "city heralds",
        "form_family": "city_symphony",
        "vfx_family": "skyline_movements",
    },
    {
        "name": "Aurora Leviathan",
        "slug": "aurora-leviathan",
        "rarity": "Divine",
        "price": 1000000,
        "duration_ms": 25000,
        "idea": "An aurora leviathan whose body is sky; it coils protectively around the entire stream UI.",
        "model": "Leviathan body as aurora volume ribbon with facial crest.",
        "environment": "Entire viewport becomes polar sky.",
        "phases": ["horizon appear", "rise", "coil protect", "eye contact", "gift scale", "sky remain"],
        "vfx": ["body aurora", "global sky override"],
        "particles": "polar glitter",
        "shaders": ["aurora volume"],
        "camera": "god-scale leviathan",
        "music": "leviathan hymn",
        "spatial": "full-dome",
        "voice": "leviathan low hymn",
        "form_family": "aurora_leviathan",
        "vfx_family": "global_aurora",
    },
    {
        "name": "Library at the End of Rain",
        "slug": "library-end-of-rain",
        "rarity": "Divine",
        "price": 2500000,
        "duration_ms": 27000,
        "idea": "After an endless rain, a library emerges; each book is a saved stream moment.",
        "model": "Rain world, emerging library, books as memory crystals.",
        "environment": "Rain plains to cathedral library (water then dry).",
        "phases": ["endless rain", "waters part", "library rise", "books orbit", "choose memory", "gift crystal"],
        "vfx": ["rain curtain", "waters part", "memory projections"],
        "particles": "rain then dry dust of light",
        "shaders": ["wet world", "library sacred"],
        "camera": "weather epic to intimate book",
        "music": "rain to silence to choir",
        "spatial": "rain muffling to hall",
        "voice": "librarian of rain",
        "form_family": "rain_library",
        "vfx_family": "memory_books",
    },
    {
        "name": "Clockwork Angel",
        "slug": "clockwork-angel",
        "rarity": "Divine",
        "price": 5000000,
        "duration_ms": 28000,
        "idea": "A clockwork angel descends, rewinds a hard moment, and gifts a second chance emblem.",
        "model": "Angel with mechanical wings, clock core, emblem.",
        "environment": "Storm city that rewinds (lightning as storm context).",
        "phases": ["storm", "descent", "rewind streets", "calm", "emblem gift", "ascent"],
        "vfx": ["storm lightning", "rewind trails", "wing gears"],
        "particles": "time shards",
        "shaders": ["feather-metal hybrid"],
        "camera": "descent mythic",
        "music": "rewind suite",
        "spatial": "storm to calm",
        "voice": "angel chime speech",
        "form_family": "clock_angel",
        "vfx_family": "rewind_storm",
    },
    {
        "name": "Seed of All Streams",
        "slug": "seed-of-all-streams",
        "rarity": "Divine",
        "price": 10000000,
        "duration_ms": 30000,
        "idea": "A primordial seed contains every SYLORA stream as floating light; it plants a future forest.",
        "model": "Seed world interior, micro-stream orbs, forest future.",
        "environment": "Interior seed cosmos to exterior forest future.",
        "phases": ["seed float", "enter interior", "orb streams", "plant", "forest future", "crest"],
        "vfx": ["interior cosmos", "forest growth time-lapse"],
        "particles": "stream orbs",
        "shaders": ["seed shell", "future foliage"],
        "camera": "inception-like scale shifts",
        "music": "primordial to future suite",
        "spatial": "inside seed to forest",
        "voice": "origin guide",
        "form_family": "stream_seed",
        "vfx_family": "seed_cosmos",
    },
    {
        "name": "Palace of Soft Thunder",
        "slug": "palace-of-soft-thunder",
        "rarity": "Divine",
        "price": 2500000,
        "duration_ms": 26000,
        "idea": "A palace where thunder is gentle light; rooms stage gifts for streamer, AI, and viewers.",
        "model": "Palace wings, soft thunder volumes, three gift altars.",
        "environment": "Multi-wing palace with weather as light.",
        "phases": ["gate", "hall of streamer", "hall of AI", "hall of viewers", "united altar"],
        "vfx": ["soft thunder light (not harsh bolts spam)", "altar blooms"],
        "particles": "palace motes",
        "shaders": ["palace marble luminous"],
        "camera": "palace tour",
        "music": "soft thunder suite",
        "spatial": "wing-by-wing",
        "voice": "palace steward",
        "form_family": "soft_thunder_palace",
        "vfx_family": "gentle_thunder",
    },
    {
        "name": "Weaver of Horizons",
        "slug": "weaver-of-horizons",
        "rarity": "Divine",
        "price": 5000000,
        "duration_ms": 28000,
        "idea": "A cosmic weaver looms horizons together so separated communities share one sunset.",
        "model": "Weaver character, loom of light, horizon ribbons, community silhouettes.",
        "environment": "Cosmic loom above multiple lands.",
        "phases": ["lands apart", "loom spin", "horizons weave", "shared sunset", "gift tapestry"],
        "vfx": ["horizon ribbons", "sunset merge"],
        "particles": "thread stars",
        "shaders": ["cosmic textile"],
        "camera": "loom god-view to human sunset",
        "music": "weave suite",
        "spatial": "cosmic to intimate",
        "voice": "weaver mantra",
        "form_family": "horizon_weaver",
        "vfx_family": "horizon_merge",
    },
    {
        "name": "Sanctum of Returning Light",
        "slug": "sanctum-returning-light",
        "rarity": "Divine",
        "price": 1000000,
        "duration_ms": 24000,
        "idea": "Lost light from past streams returns to a sanctum and reforms as a living crest.",
        "model": "Sanctum architecture, returning light ribbons, living crest creature.",
        "environment": "Sanctum interior with memory apertures.",
        "phases": ["dark sanctum", "lights return", "weave crest", "crest awakens", "bless stream"],
        "vfx": ["returning ribbons", "crest life"],
        "particles": "memory sparks",
        "shaders": ["sanctum stone", "living light"],
        "camera": "sanctum sacred coverage",
        "music": "returning light hymn",
        "spatial": "sacred hall",
        "voice": "sanctum choir",
        "form_family": "light_sanctum",
        "vfx_family": "returning_ribbons",
    },
    {
        "name": "Starforge Ballet",
        "slug": "starforge-ballet",
        "rarity": "Divine",
        "price": 2500000,
        "duration_ms": 27000,
        "idea": "Dancers forge stars with their steps; finale plants a new star above the streamer.",
        "model": "Multiple dancer characters, starforge floor, new star.",
        "environment": "Cosmic stage with forge floor (stylized stellar fire under glass).",
        "phases": ["overture", "dance forge", "star birth", "lift star", "plant above", "bow"],
        "vfx": ["stellar forge under glass", "star birth"],
        "particles": "stellar sparks",
        "shaders": ["dance bodies", "star materials"],
        "camera": "ballet cinema",
        "music": "ballet starforge suite",
        "spatial": "stage cosmic",
        "voice": "none",
        "form_family": "starforge_ballet",
        "vfx_family": "dance_stars",
    },
    {
        "name": "Ark of Soft Seasons",
        "slug": "ark-of-soft-seasons",
        "rarity": "Divine",
        "price": 5000000,
        "duration_ms": 29000,
        "idea": "An ark sails through spring, summer, autumn, winter rooms; each leaves a seasonal gift layer.",
        "model": "Ark vessel, four seasonal chambers with unique flora/props.",
        "environment": "Multi-season ark interior voyage.",
        "phases": ["embark", "spring", "summer", "autumn", "winter", "combined wreath gift"],
        "vfx": ["season-unique (blossoms, heat shimmer, leaves, snow) — fire only if winter hearth cameo"],
        "particles": "per season",
        "shaders": ["per season art"],
        "camera": "ark voyage",
        "music": "four seasons original suite",
        "spatial": "chamber acoustics",
        "voice": "season heralds",
        "form_family": "season_ark",
        "vfx_family": "four_seasons",
    },
    {
        "name": "Crown of Shared Silence",
        "slug": "crown-of-shared-silence",
        "rarity": "Divine",
        "price": 10000000,
        "duration_ms": 30000,
        "idea": "The rarest gift: a shared minute of beautiful silence visualized as a crystal crown forming from quiet.",
        "model": "Crystal crown assembling from silence rings; audience lights dim elegantly.",
        "environment": "World reduces to quiet geometry and breath light.",
        "phases": ["noise fall away", "silence rings", "crown assemble", "shared hold", "soft return", "crest"],
        "vfx": ["silence visualized as clear rings", "soft breath light — no fireworks"],
        "particles": "almost none — intentional sparsity",
        "shaders": ["ultra clear crystal"],
        "camera": "ultra slow sacred moves",
        "music": "near-silence with heart-adjacent pulse",
        "spatial": "extreme quiet mix",
        "voice": "none — silence is the VO",
        "form_family": "silence_crown",
        "vfx_family": "sacred_quiet",
    },
    {
        "name": "SYLORA Eternal Hearth",
        "slug": "sylora-eternal-hearth",
        "rarity": "Divine",
        "price": 5000000,
        "duration_ms": 28000,
        "idea": "A hearth that never consumes — warmth without harm — gathering every creator into one home light.",
        "model": "Eternal hearth architecture, gathering figures, home light orb.",
        "environment": "Home of homes — many doorways into one hearth hall (contained hearth fire).",
        "phases": ["doors open", "creators arrive", "hearth kindles (safe fire)", "stories orbit", "home orb gift"],
        "vfx": ["safe hearth fire", "story orbits", "home light"],
        "particles": "embers that become fireflies",
        "shaders": ["warm home materials"],
        "camera": "hearth gathering cinema",
        "music": "home eternal suite",
        "spatial": "intimate vast hall",
        "voice": "many soft welcomes",
        "form_family": "eternal_hearth",
        "vfx_family": "safe_hearth",
    },
]


def build_spec(gift: dict, index: int) -> dict:
    rarity = gift["rarity"]
    duration = gift["duration_ms"]
    asset_ids = {
        "glb": str(uuid.uuid5(uuid.NAMESPACE_URL, f"sylora:gift:{gift['slug']}:glb")),
        "audio": str(uuid.uuid5(uuid.NAMESPACE_URL, f"sylora:gift:{gift['slug']}:audio")),
        "poster": str(uuid.uuid5(uuid.NAMESPACE_URL, f"sylora:gift:{gift['slug']}:poster")),
        "blend": str(uuid.uuid5(uuid.NAMESPACE_URL, f"sylora:gift:{gift['slug']}:blend")),
        "shader": str(uuid.uuid5(uuid.NAMESPACE_URL, f"sylora:gift:{gift['slug']}:shader")),
    }
    return {
        "index": index,
        "name": gift["name"],
        "slug": gift["slug"],
        "cost": gift["price"],
        "price_minor": gift["price"],
        "rarity": rarity,
        "api_tier": API_TIER[rarity],
        "duration_ms": duration,
        "duration_sec": round(duration / 1000, 2),
        "main_idea": gift["idea"],
        "model_description": gift["model"],
        "environment_description": gift["environment"],
        "animation_phases": gift["phases"],
        "vfx": gift["vfx"],
        "lighting": {
            "hdri": True,
            "bloom": True,
            "motion_blur": rarity in {"Legendary", "Mythic", "Divine"},
            "depth_of_field": True,
            "lens_flare": "justified" if "flare" in " ".join(gift["vfx"]).lower() or rarity == "Divine" else "none",
        },
        "particles": gift["particles"],
        "shaders": gift["shaders"],
        "camera": gift["camera"],
        "music": gift["music"],
        "spatial_sound": gift["spatial"],
        "voice_effects": gift["voice"],
        "ai_reaction": f"AI acknowledges '{gift['name']}' with a rarity-appropriate line and never fabricates delivery.",
        "streamer_reaction": "Streamer avatar/emote hook on arrival + optional thank-you prompt.",
        "avatar_reaction": "Avatar glance/emote timed to completion hook.",
        "viewer_reaction": "Viewer-side fullscreen or scoped effect per rarity.",
        "chat_reaction": "Chat system message with gift name, sender, and rarity badge.",
        "combo_reaction": f"Combination id sylora.gift.{gift['slug']} with window based on rarity.",
        "performance_targets": {
            "mobile_fps_min": 30 if rarity in {"Rare", "Epic"} else 24,
            "desktop_fps_min": 60 if rarity in {"Rare", "Epic", "Legendary"} else 45,
            "max_memory_mb": { "Rare": 48, "Epic": 96, "Legendary": 160, "Mythic": 220, "Divine": 320 }[rarity],
            "max_load_ms": { "Rare": 800, "Epic": 1500, "Legendary": 2500, "Mythic": 4000, "Divine": 6000 }[rarity],
        },
        "mobile_lod": "reduced particles, simplified materials, no motion blur",
        "desktop_ultra": "full particles, HDR, bloom, DoF, motion blur when specified",
        "form_family": gift["form_family"],
        "vfx_family": gift["vfx_family"],
        "asset_ids": asset_ids,
        "paths": {
            "glb": f"artifacts/gift-library/{gift['slug']}/model.glb",
            "blender": f"artifacts/gift-library/{gift['slug']}/scene.blend",
            "runtime_manifest": f"artifacts/gift-library/{gift['slug']}/runtime-manifest.json",
            "metadata": f"artifacts/gift-library/{gift['slug']}/metadata.json",
            "preview_video": f"artifacts/gift-library/{gift['slug']}/preview.mp4",
            "gif_preview": f"artifacts/gift-library/{gift['slug']}/preview.gif",
            "thumbnail": f"artifacts/gift-library/{gift['slug']}/poster.png",
            "sound_pack": f"artifacts/gift-library/{gift['slug']}/sound/",
            "particle_pack": f"artifacts/gift-library/{gift['slug']}/particles/",
            "report": f"artifacts/gift-library/{gift['slug']}/report.json",
        },
        # Honest default — never READY until pipeline validates real assets.
        "status": "SPEC_ONLY",
        "ready_checklist": {
            "real_3d_model": False,
            "real_animation": False,
            "real_vfx": False,
            "real_sound": False,
            "runtime_preview": False,
            "sylora_integration": False,
            "video_proof": False,
            "performance_check": False,
        },
        "known_limitations": [
            "Specification only until Blender/GLB/audio/preview/runtime evidence is produced and verified.",
            "AAA art-pass and performance-pass require specialized DCC artists beyond this agent environment.",
        ],
    }


def main() -> None:
    assert len(GIFTS) == 100, f"expected 100 gifts, got {len(GIFTS)}"
    slugs = [g["slug"] for g in GIFTS]
    assert len(set(slugs)) == 100, "duplicate slugs"
    names = [g["name"] for g in GIFTS]
    assert len(set(names)) == 100, "duplicate names"
    families = [g["form_family"] for g in GIFTS]
    assert len(set(families)) == 100, "form_family must be unique per gift (no color clones)"

    rarity_counts = {"Rare": 0, "Epic": 0, "Legendary": 0, "Mythic": 0, "Divine": 0}
    for g in GIFTS:
        rarity_counts[g["rarity"]] += 1
    assert rarity_counts == {"Rare": 20, "Epic": 20, "Legendary": 20, "Mythic": 20, "Divine": 20}

    OUT.mkdir(parents=True, exist_ok=True)
    catalog = []
    for i, gift in enumerate(GIFTS, start=1):
        spec = build_spec(gift, i)
        gift_dir = OUT / gift["slug"]
        gift_dir.mkdir(parents=True, exist_ok=True)
        (gift_dir / "sound").mkdir(exist_ok=True)
        (gift_dir / "particles").mkdir(exist_ok=True)
        (gift_dir / "spec.json").write_text(json.dumps(spec, indent=2) + "\n", encoding="utf-8")
        catalog.append({
            "index": i,
            "name": spec["name"],
            "slug": spec["slug"],
            "rarity": spec["rarity"],
            "api_tier": spec["api_tier"],
            "cost": spec["cost"],
            "duration_ms": spec["duration_ms"],
            "status": spec["status"],
            "form_family": spec["form_family"],
            "vfx_family": spec["vfx_family"],
        })

    summary = {
        "project": "SYLORA",
        "library": "Official Gift Library",
        "total": 100,
        "rarity_counts": rarity_counts,
        "ready_count": 0,
        "spec_only_count": 100,
        "policy": "READY only after real 3D, animation, VFX, sound, runtime preview, SYLORA integration, video proof, and performance checks.",
        "gifts": catalog,
    }
    (OUT / "catalog.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    names_path = OUT / "NAMES.md"
    lines = ["# SYLORA Official Gift Library — 100 Names\n", f"Branch artifacts under `{OUT}`\n"]
    for rarity in ["Rare", "Epic", "Legendary", "Mythic", "Divine"]:
        lines.append(f"\n## {rarity}\n")
        for item in catalog:
            if item["rarity"] == rarity:
                lines.append(f"- {item['index']:03d}. **{item['name']}** (`{item['slug']}`) — {item['cost']} — {item['status']}\n")
    names_path.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {len(catalog)} specs to {OUT}")
    print(json.dumps(rarity_counts))


if __name__ == "__main__":
    main()
