listening-port=3478
listening-ip=0.0.0.0
min-port=49160
max-port=49200

fingerprint
lt-cred-mech
stale-nonce=600

no-cli
no-tls
no-dtls
no-tcp-relay
no-multicast-peers

user-quota=4
total-quota=40
max-bps=20000000
bps-capacity=1000000000

prometheus
prometheus-address=0.0.0.0
prometheus-port=9641
prometheus-path=/metrics

log-file=stdout
simple-log
