apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sylora-api
  labels:
    app.kubernetes.io/name: sylora-api
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app.kubernetes.io/name: sylora-api
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sylora-celery-worker
  labels:
    app.kubernetes.io/name: sylora-celery-worker
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app.kubernetes.io/name: sylora-celery-worker
      app.kubernetes.io/component: worker
