apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sylora-mediamtx-recordings
  labels:
    app.kubernetes.io/name: sylora-mediamtx
    app.kubernetes.io/component: recording
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
