// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/design-variants/ConceptDash.tsx": () => import("../components/mockups/design-variants/ConceptDash.tsx"),
  "./components/mockups/design-variants/CyberNeon.tsx": () => import("../components/mockups/design-variants/CyberNeon.tsx"),
  "./components/mockups/design-variants/IceAurora.tsx": () => import("../components/mockups/design-variants/IceAurora.tsx"),
  "./components/mockups/design-variants/PlasmaStorm.tsx": () => import("../components/mockups/design-variants/PlasmaStorm.tsx")
};
