// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/design-variants/ConceptDash.tsx": () => import("../components/mockups/design-variants/ConceptDash.tsx"),
  "./components/mockups/design-variants/CyberNeon.tsx": () => import("../components/mockups/design-variants/CyberNeon.tsx"),
  "./components/mockups/design-variants/IceAurora.tsx": () => import("../components/mockups/design-variants/IceAurora.tsx"),
  "./components/mockups/design-variants/PlasmaStorm.tsx": () => import("../components/mockups/design-variants/PlasmaStorm.tsx"),
  "./components/mockups/font-compare/Inter.tsx": () => import("../components/mockups/font-compare/Inter.tsx"),
  "./components/mockups/font-compare/Outfit.tsx": () => import("../components/mockups/font-compare/Outfit.tsx"),
  "./components/mockups/font-compare/Sora.tsx": () => import("../components/mockups/font-compare/Sora.tsx"),
  "./components/mockups/font-compare/SpaceGrotesk.tsx": () => import("../components/mockups/font-compare/SpaceGrotesk.tsx"),
  "./components/mockups/stage/LiveStormStagePreview.tsx": () => import("../components/mockups/stage/LiveStormStagePreview.tsx"),
  "./components/mockups/ui-themes/Arctic.tsx": () => import("../components/mockups/ui-themes/Arctic.tsx"),
  "./components/mockups/ui-themes/Cherry.tsx": () => import("../components/mockups/ui-themes/Cherry.tsx"),
  "./components/mockups/ui-themes/DeepOcean.tsx": () => import("../components/mockups/ui-themes/DeepOcean.tsx"),
  "./components/mockups/ui-themes/Emerald.tsx": () => import("../components/mockups/ui-themes/Emerald.tsx"),
  "./components/mockups/ui-themes/GoldRush.tsx": () => import("../components/mockups/ui-themes/GoldRush.tsx"),
  "./components/mockups/ui-themes/Midnight.tsx": () => import("../components/mockups/ui-themes/Midnight.tsx"),
  "./components/mockups/ui-themes/NeonPulse.tsx": () => import("../components/mockups/ui-themes/NeonPulse.tsx"),
  "./components/mockups/ui-themes/Noir.tsx": () => import("../components/mockups/ui-themes/Noir.tsx"),
  "./components/mockups/ui-themes/Pastel.tsx": () => import("../components/mockups/ui-themes/Pastel.tsx"),
  "./components/mockups/ui-themes/Sunset.tsx": () => import("../components/mockups/ui-themes/Sunset.tsx")
};
